version: 0.2

phases:
  pre_build:
    commands:
      - npm install newman --global
      - npm install newman-reporter-html --global
      - TIME=$(date +"%Y-%m-%d-%H-%M-%S")
      - REPOSITORY_NAME="automation-test-report"
      - COLLECTION=$(aws s3 ls ${REPOSITORY_NAME}/postman/ | grep collection | tail -1 | awk '{print $NF}')
      - ENVIRONMENT=$(aws s3 ls ${REPOSITORY_NAME}/postman/ | grep environment | tail -1 | awk '{print $NF}')
      - aws s3 cp s3://${REPOSITORY_NAME}/postman/${COLLECTION} collection.json
      - aws s3 cp s3://${REPOSITORY_NAME}/postman/${ENVIRONMENT} environment.json
  build:
    commands:
      - newman run -r html,cli "collection.json" -e "environment.json" --reporter-html-export report.html
  post_build:
    commands:
      - ls -al
      - aws s3 cp report.html s3://${REPOSITORY_NAME}/postman-report/report-${TIME}.html
